#! /usr/bin/env python
"""usage: ./run-test

Run one Container Test"""

import os
from support import ContainerTestsuite

if __name__ == '__main__':
    ContainerTestsuite(os.path.dirname(__file__)).test_main()
